name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tear down any running containers
        run: docker compose down

      - name: Build Docker images with no cache
        run: docker compose build --no-cache

      - name: Start services (force recreate)
        run: docker compose up -d --force-recreate

      - name: Check API health
        run: |
          sleep 10  # wait for containers to be ready
          curl --fail http://localhost:3030/ || (echo "API not healthy" && exit 1)

      - name: Tear down Docker Compose (after tests)
        run: docker compose down