name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (from Dockerfile)
        run: docker build -t pyapi .

      - name: Docker Compose up (optional, for integration)
        run: |
          if [ -f compose.yml ]; then
            docker compose -f compose.yml up -d
          fi